export default function AdminQuyBaoTriPage() {
  return (
    <div className="adm-r-quy-bao-tri">
      <div className="mg-page">
            <div className="mg-hd">
              <div><h1 className="mg-title">Quỹ bảo trì</h1><p className="mg-sub">Quản lý số dư, thu chi và lãi suất quỹ bảo trì tòa nhà</p></div>
              <button className="mg-btn"><svg viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg> Ghi nhận giao dịch</button>
            </div>
            <div className="mg-stats"><div className="mg-stat"><div className="mg-stat-ic" style={{ background: "#e4f1ff" }}><svg viewBox="0 0 24 24" fill="none" stroke="#2f7bf6" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3" /><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3" /><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5" /></svg></div><div><div className="mg-stat-val">8,265 tỷ</div><div className="mg-stat-lbl">Số dư quỹ hiện tại</div></div></div><div className="mg-stat"><div className="mg-stat-ic" style={{ background: "#e6f7f1" }}><svg viewBox="0 0 24 24" fill="none" stroke="#1c9d5f" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18" /><polyline points="17 6 23 6 23 12" /></svg></div><div><div className="mg-stat-val">94,9 tr</div><div className="mg-stat-lbl">Thu trong tháng</div></div></div><div className="mg-stat"><div className="mg-stat-ic" style={{ background: "#ffeded" }}><svg viewBox="0 0 24 24" fill="none" stroke="#f5222d" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 18 13.5 8.5 8.5 13.5 1 6" /><polyline points="17 18 23 18 23 12" /></svg></div><div><div className="mg-stat-val">259,8 tr</div><div className="mg-stat-lbl">Đã chi tháng</div></div></div><div className="mg-stat"><div className="mg-stat-ic" style={{ background: "#efffe7" }}><svg viewBox="0 0 24 24" fill="none" stroke="#1c9d5f" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="8" cy="8" r="6" /><path d="M18.09 10.37A6 6 0 1 1 10.34 18" /><path d="M7 6h1v4" /></svg></div><div><div className="mg-stat-val">165,3 tr</div><div className="mg-stat-lbl">Lãi tích lũy năm</div></div></div></div>
            
            <div className="mg-toolbar">
              <div className="mg-search"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7" /><line x1="20" y1="20" x2="16.65" y2="16.65" /></svg><input placeholder="Tìm kiếm..." /></div>
              <div className="mg-filter">Lọc <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9" /></svg></div>
            </div>
            <div className="mg-card">
              <table className="mg-tbl"><thead><tr><th>Ngày</th><th>Nội dung</th><th>Loại</th><th>Số tiền</th></tr></thead><tbody><tr><td>01/06/2026</td><td><div className="mg-pname">Trích 2% phí dịch vụ T5</div></td><td><span className="mg-pill s-green">Thu</span></td><td style={{ fontWeight: "700", color: "#1c9d5f" }}>+53.600.000đ</td></tr><tr><td>28/05/2026</td><td><div className="mg-pname">Sửa chữa hệ thống bơm nước</div></td><td><span className="mg-pill s-red">Chi</span></td><td style={{ fontWeight: "700", color: "#f5222d" }}>-78.000.000đ</td></tr><tr><td>15/05/2026</td><td><div className="mg-pname">Lãi tiền gửi ngân hàng Q2</div></td><td><span className="mg-pill s-green">Thu</span></td><td style={{ fontWeight: "700", color: "#1c9d5f" }}>+41.325.000đ</td></tr><tr><td>10/05/2026</td><td><div className="mg-pname">Sơn lại sảnh tầng trệt tháp B</div></td><td><span className="mg-pill s-red">Chi</span></td><td style={{ fontWeight: "700", color: "#f5222d" }}>-125.000.000đ</td></tr><tr><td>05/05/2026</td><td><div className="mg-pname">Thay thế thiết bị PCCC</div></td><td><span className="mg-pill s-red">Chi</span></td><td style={{ fontWeight: "700", color: "#f5222d" }}>-56.800.000đ</td></tr></tbody></table>
              <div className="mg-foot"><div className="mg-count">Hiển thị 1 - 8 của 86 giao dịch</div><div className="mg-pages"><span className="mg-pg">‹</span><span className="mg-pg active">1</span><span className="mg-pg">2</span><span className="mg-pg">3</span><span className="mg-pg">›</span></div></div>
            </div>
          </div>
    </div>
  );
}
